{{- if .Values.secrets.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "auvora-wallet.fullname" . }}-external
  namespace: {{ include "auvora-wallet.namespace" . }}
  labels:
    {{- include "auvora-wallet.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.secrets.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ include "auvora-wallet.secretName" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range .Values.secrets.externalSecret.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.secrets.externalSecret.remoteKey }}
        property: {{ . }}
    {{- end }}
{{- end }}
