{{- if .Values.ingress.enabled }}
{{- $multi := and .Values.ingress.hosts (gt (len .Values.ingress.hosts) 0) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "auvora-wallet.fullname" . }}
  namespace: {{ include "auvora-wallet.namespace" . }}
  labels:
    {{- include "auvora-wallet.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- if $multi }}
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
    {{- else }}
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if $multi }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .backend }}
                port:
                  number: {{ .port }}
    {{- end }}
    {{- else }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if .Values.apps.web.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: {{ .Values.apps.web.port }}
          {{- end }}
          {{- if .Values.apps.admin.enabled }}
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: {{ .Values.apps.admin.port }}
          {{- end }}
          {{- if .Values.services.gateway.enabled }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: {{ .Values.services.gateway.port }}
          {{- end }}
    {{- end }}
{{- end }}
