export const CONNECTIONS_EVENTS = {
  DEVICE_PAIRED: 'connections.device.paired',
  DEVICE_DISCONNECTED: 'connections.device.disconnected',
  SESSION_CREATED: 'connections.session.created',
  SESSION_APPROVED: 'connections.session.approved',
  SESSION_REJECTED: 'connections.session.rejected',
  SESSION_TERMINATED: 'connections.session.terminated',
  WATCH_ADDED: 'connections.watch.added',
  SIGN_PREPARED: 'connections.sign.prepared',
  SIGN_COMPLETED: 'connections.sign.completed',
  SIGN_FAILED: 'connections.sign.failed',
  DAPP_REQUEST_CREATED: 'connections.dapp.request.created',
  DAPP_REQUEST_APPROVED: 'connections.dapp.request.approved',
  DAPP_REQUEST_REJECTED: 'connections.dapp.request.rejected',
  DAPP_TRUSTED: 'connections.dapp.trusted',
  DAPP_REVOKED: 'connections.dapp.revoked',
  DAPP_PERMISSION_UPDATED: 'connections.dapp.permission.updated',
  DAPP_BROWSER_VISITED: 'connections.dapp.browser.visited',
} as const;
