-- AlterEnum (must target AuditAction ? SecurityAuditLog.action uses AuditAction)
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACCEPTANCE_PASSWORD_RESET_MINTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACCEPTANCE_VAULT_RECOVERY_FORCE_EXPIRED';
