-- AlterEnum
ALTER TYPE "SecurityAuditAction" ADD VALUE IF NOT EXISTS 'ACCEPTANCE_PASSWORD_RESET_MINTED';
ALTER TYPE "SecurityAuditAction" ADD VALUE IF NOT EXISTS 'ACCEPTANCE_VAULT_RECOVERY_FORCE_EXPIRED';
